/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMyScoresRouteImport } from './routes/_authenticated/my.scores'
import { Route as AuthenticatedEbAssistantRouteImport } from './routes/_authenticated/eb.assistant'
import { Route as AuthenticatedCommitteeCommitteeIdRouteImport } from './routes/_authenticated/committee.$committeeId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin.resources'
import { Route as AuthenticatedAdminConferencesRouteImport } from './routes/_authenticated/admin.conferences'
import { Route as AuthenticatedAdminCommitteesRouteImport } from './routes/_authenticated/admin.committees'
import { Route as AuthenticatedAdminCmsRouteImport } from './routes/_authenticated/admin.cms'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyScoresRoute = AuthenticatedMyScoresRouteImport.update({
  id: '/my/scores',
  path: '/my/scores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbAssistantRoute =
  AuthenticatedEbAssistantRouteImport.update({
    id: '/eb/assistant',
    path: '/eb/assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommitteeCommitteeIdRoute =
  AuthenticatedCommitteeCommitteeIdRouteImport.update({
    id: '/committee/$committeeId',
    path: '/committee/$committeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/admin/resources',
    path: '/admin/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConferencesRoute =
  AuthenticatedAdminConferencesRouteImport.update({
    id: '/admin/conferences',
    path: '/admin/conferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCommitteesRoute =
  AuthenticatedAdminCommitteesRouteImport.update({
    id: '/admin/committees',
    path: '/admin/committees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCmsRoute = AuthenticatedAdminCmsRouteImport.update({
  id: '/admin/cms',
  path: '/admin/cms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/editions': typeof EditionsRoute
  '/faq': typeof FaqRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/committees': typeof AuthenticatedAdminCommitteesRoute
  '/admin/conferences': typeof AuthenticatedAdminConferencesRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/$committeeId': typeof AuthenticatedCommitteeCommitteeIdRoute
  '/eb/assistant': typeof AuthenticatedEbAssistantRoute
  '/my/scores': typeof AuthenticatedMyScoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/editions': typeof EditionsRoute
  '/faq': typeof FaqRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/committees': typeof AuthenticatedAdminCommitteesRoute
  '/admin/conferences': typeof AuthenticatedAdminConferencesRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/$committeeId': typeof AuthenticatedCommitteeCommitteeIdRoute
  '/eb/assistant': typeof AuthenticatedEbAssistantRoute
  '/my/scores': typeof AuthenticatedMyScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/editions': typeof EditionsRoute
  '/faq': typeof FaqRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/_authenticated/admin/committees': typeof AuthenticatedAdminCommitteesRoute
  '/_authenticated/admin/conferences': typeof AuthenticatedAdminConferencesRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/committee/$committeeId': typeof AuthenticatedCommitteeCommitteeIdRoute
  '/_authenticated/eb/assistant': typeof AuthenticatedEbAssistantRoute
  '/_authenticated/my/scores': typeof AuthenticatedMyScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/awards'
    | '/committees'
    | '/contact'
    | '/editions'
    | '/faq'
    | '/register'
    | '/dashboard'
    | '/resources'
    | '/admin/login'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/cms'
    | '/admin/committees'
    | '/admin/conferences'
    | '/admin/resources'
    | '/admin/users'
    | '/committee/$committeeId'
    | '/eb/assistant'
    | '/my/scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/awards'
    | '/committees'
    | '/contact'
    | '/editions'
    | '/faq'
    | '/register'
    | '/dashboard'
    | '/resources'
    | '/admin/login'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/cms'
    | '/admin/committees'
    | '/admin/conferences'
    | '/admin/resources'
    | '/admin/users'
    | '/committee/$committeeId'
    | '/eb/assistant'
    | '/my/scores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/awards'
    | '/committees'
    | '/contact'
    | '/editions'
    | '/faq'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/resources'
    | '/admin/login'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/cms'
    | '/_authenticated/admin/committees'
    | '/_authenticated/admin/conferences'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/users'
    | '/_authenticated/committee/$committeeId'
    | '/_authenticated/eb/assistant'
    | '/_authenticated/my/scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  CommitteesRoute: typeof CommitteesRoute
  ContactRoute: typeof ContactRoute
  EditionsRoute: typeof EditionsRoute
  FaqRoute: typeof FaqRoute
  RegisterRoute: typeof RegisterRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my/scores': {
      id: '/_authenticated/my/scores'
      path: '/my/scores'
      fullPath: '/my/scores'
      preLoaderRoute: typeof AuthenticatedMyScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eb/assistant': {
      id: '/_authenticated/eb/assistant'
      path: '/eb/assistant'
      fullPath: '/eb/assistant'
      preLoaderRoute: typeof AuthenticatedEbAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee/$committeeId': {
      id: '/_authenticated/committee/$committeeId'
      path: '/committee/$committeeId'
      fullPath: '/committee/$committeeId'
      preLoaderRoute: typeof AuthenticatedCommitteeCommitteeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/conferences': {
      id: '/_authenticated/admin/conferences'
      path: '/admin/conferences'
      fullPath: '/admin/conferences'
      preLoaderRoute: typeof AuthenticatedAdminConferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/committees': {
      id: '/_authenticated/admin/committees'
      path: '/admin/committees'
      fullPath: '/admin/committees'
      preLoaderRoute: typeof AuthenticatedAdminCommitteesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cms': {
      id: '/_authenticated/admin/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AuthenticatedAdminCmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminCmsRoute: typeof AuthenticatedAdminCmsRoute
  AuthenticatedAdminCommitteesRoute: typeof AuthenticatedAdminCommitteesRoute
  AuthenticatedAdminConferencesRoute: typeof AuthenticatedAdminConferencesRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCommitteeCommitteeIdRoute: typeof AuthenticatedCommitteeCommitteeIdRoute
  AuthenticatedEbAssistantRoute: typeof AuthenticatedEbAssistantRoute
  AuthenticatedMyScoresRoute: typeof AuthenticatedMyScoresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminCmsRoute: AuthenticatedAdminCmsRoute,
  AuthenticatedAdminCommitteesRoute: AuthenticatedAdminCommitteesRoute,
  AuthenticatedAdminConferencesRoute: AuthenticatedAdminConferencesRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCommitteeCommitteeIdRoute:
    AuthenticatedCommitteeCommitteeIdRoute,
  AuthenticatedEbAssistantRoute: AuthenticatedEbAssistantRoute,
  AuthenticatedMyScoresRoute: AuthenticatedMyScoresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  CommitteesRoute: CommitteesRoute,
  ContactRoute: ContactRoute,
  EditionsRoute: EditionsRoute,
  FaqRoute: FaqRoute,
  RegisterRoute: RegisterRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
